### ISSUE TITLE
Bug with logging

### ISSUE THREAD

**Issue by derfenix** [bndr/pipreqs#11]
Traceback (most recent call last):
  File "/usr/bin/pipreqs", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 158, in main
    init(args)
  File "/usr/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 139, in init
    imports_local = get_import_local(imports)
  File "/usr/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 120, in get_import_local
    local = get_locally_installed_packages()
  File "/usr/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 110, in get_locally_installed_packages
    'Could not determine import name for package ' + package_import)
TypeError: cannot concatenate 'str' and 'list' objects

**Comment by bndr** [comment]
Should be fixed in latest version.
