### ISSUE TITLE
Windows running error:  UnicodeDecodeError: 'gbk' codec 

### ISSUE THREAD

**Issue by tanmc123** [bndr/pipreqs#125]
I use pycharm terminal to run pipreqs. And the following error occurs:

C:\Users\Mingc\OneDrive\iCarbonX\Meum\meum_nlp\nlp_v2\icx_nlp>pipreqs --use-local ./
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python36-32\Scripts\pipreqs.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python36-32\lib\site-packages\pipreqs\pipreqs.py", line 396, in main
    init(args)
  File "c:\program files (x86)\python36-32\lib\site-packages\pipreqs\pipreqs.py", line 341, in init
    extra_ignore_dirs=extra_ignore_dirs)
  File "c:\program files (x86)\python36-32\lib\site-packages\pipreqs\pipreqs.py", line 75, in get_all_imports
    contents = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa7 in position 27: illegal multibyte sequence

I have changed the file encoding setting to utf-8 but it still not works. How can I solve it?

**Comment by darren-liu** [comment]
you may try to put '--encoding=utf-8' as an argument to trigger.

**Comment by jdhao** [comment]
I think the default encoding should be UTF-8.
