### ISSUE TITLE
Add feature to parse function annotation - PEP 3107

### ISSUE THREAD

**Issue by kuharan** [bndr/pipreqs#135]
Ref to Python Function Annotations -  [PEP 3107](https://www.python.org/dev/peps/pep-3107/)

Below is the error produced.

```
ERROR: Failed on file: ./<Filename>
Traceback (most recent call last):
  File "/usr/local/bin/pipreqs", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pipreqs/pipreqs.py", line 396, in main
    init(args)
  File "/usr/local/lib/python2.7/dist-packages/pipreqs/pipreqs.py", line 341, in init
    extra_ignore_dirs=extra_ignore_dirs)
  File "/usr/local/lib/python2.7/dist-packages/pipreqs/pipreqs.py", line 91, in get_all_imports
    raise exc
  File "<unknown>", line 6
    def read_csv(src) -> list:
                      ^
SyntaxError: invalid syntax

```

**Comment by jonafato** [comment]
Function annotations are Python 3-only syntax. If you install `pipreqs` into a Python 3 environment, it should work fine.
