### ISSUE TITLE
Invalid syntax for python <3.6

### ISSUE THREAD

**Issue by tomzx** [bndr/pipreqs#136]
When running `pipreqs` using python 3.5, I get the following error:

```
ERROR: Failed on file: X:\X.py
Traceback (most recent call last):
  File "c:\users\tom\appdata\local\programs\python\python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\tom\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python35\Scripts\pipreqs.exe\__main__.py", line 9, in <module>
  File "c:\users\tom\appdata\local\programs\python\python35\lib\site-packages\pipreqs\pipreqs.py", line 396, in main
    init(args)
  File "c:\users\tom\appdata\local\programs\python\python35\lib\site-packages\pipreqs\pipreqs.py", line 341, in init
    extra_ignore_dirs=extra_ignore_dirs)
  File "c:\users\tom\appdata\local\programs\python\python35\lib\site-packages\pipreqs\pipreqs.py", line 91, in get_all_imports
    raise exc
  File "c:\users\tom\appdata\local\programs\python\python35\lib\site-packages\pipreqs\pipreqs.py", line 77, in get_all_imports
    tree = ast.parse(contents)
  File "c:\users\tom\appdata\local\programs\python\python35\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 11
    print(f'Loading file {args.input}')
                                     ^
SyntaxError: invalid syntax
```

This string uses [f-strings](https://docs.python.org/3/reference/lexical_analysis.html#f-strings), which are only available after python 3.6. In your `setup.py`

https://github.com/bndr/pipreqs/blob/0b8c38ce415f7416ae115037a41c4b17655357b6/setup.py#L47-L50

it lists 2.7, 3.4 and 3.5, but those can't work due to the use of f-strings.

**Comment by jonafato** [comment]
I don't see any f-strings in the `pipreqs` source on `master` or the latest release. Perhaps this f-string is in the source that `pipreqs` is trying to read?

**Comment by tomzx** [comment]
@jonafato Correct. This appears to be the source code I am scanning. Apparently `pipreqs` must be able to parse the AST of the source file using the python version it is using. As such, it can't parse 3.6+ with 3.5.

At this point I guess the best would be simply to notify users that they can't parse a file with more recent syntax using an older version of python.

**Comment by jonafato** [comment]
Correct, `pipreqs` installed to a Python 3.5 environment will be unable to parse source code containing 3.6-only features. I'd recommend installing `pipreqs` into a virtual environment alongside your testing, linting, and other development utilities with your intended Python version.

I'm going to close this issue, as it does not appear to be a bug in `pipreqs`. If you have a viable approach to gracefully handle errors like these, I'd accept a pull request.
