### ISSUE TITLE
error if sys.exit

### ISSUE THREAD

**Issue by Niccolum** [bndr/pipreqs#150]
pipreqs /home/nicky/
ERROR: Failed on file: /home/nicky/projects/DjangoBI/files/tests/csv_load_tests.py
Traceback (most recent call last):
  File "/usr/local/bin/pipreqs", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pipreqs/pipreqs.py", line 396, in main
    init(args)
  File "/usr/local/lib/python3.5/dist-packages/pipreqs/pipreqs.py", line 341, in init
    extra_ignore_dirs=extra_ignore_dirs)
  File "/usr/local/lib/python3.5/dist-packages/pipreqs/pipreqs.py", line 91, in get_all_imports
    raise exc
  File "/usr/local/lib/python3.5/dist-packages/pipreqs/pipreqs.py", line 77, in get_all_imports
    tree = ast.parse(contents)
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 75
    def int_func(self):
      ^
IndentationError: expected an indented block

**Comment by lonngxiang** [comment]
same issue，how to fix？
