### ISSUE TITLE
Python2 breaking the code in Python3

### ISSUE THREAD

**Issue by abhiksark** [bndr/pipreqs#178]
Traceback (most recent call last):
  File "/home/aodev/anaconda3/bin/pipreqs", line 10, in <module>
    sys.exit(main())
  File "/home/aodev/anaconda3/lib/python3.7/site-packages/pipreqs/pipreqs.py", line 470, in main
    init(args)
  File "/home/aodev/anaconda3/lib/python3.7/site-packages/pipreqs/pipreqs.py", line 409, in init
    follow_links=follow_links)
  File "/home/aodev/anaconda3/lib/python3.7/site-packages/pipreqs/pipreqs.py", line 138, in get_all_imports
    raise exc
  File "/home/aodev/anaconda3/lib/python3.7/site-packages/pipreqs/pipreqs.py", line 124, in get_all_imports
    tree = ast.parse(contents)
  File "/home/aodev/anaconda3/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 422
    print 'fg total num:', len(fg_indexes)
                        ^
SyntaxError: invalid syntax

**Comment by Z1Wu** [comment]
Same problem when trying to generae a requement.txt of a Django project
```
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/learn_pytorch/bin/pipreqs", line 10, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/envs/learn_pytorch/lib/python3.7/site-packages/pipreqs/pipreqs.py", line 470, in main
    init(args)
  File "/usr/local/anaconda3/envs/learn_pytorch/lib/python3.7/site-packages/pipreqs/pipreqs.py", line 409, in init
    follow_links=follow_links)
  File "/usr/local/anaconda3/envs/learn_pytorch/lib/python3.7/site-packages/pipreqs/pipreqs.py", line 138, in get_all_imports
    raise exc
  File "/usr/local/anaconda3/envs/learn_pytorch/lib/python3.7/site-packages/pipreqs/pipreqs.py", line 124, in get_all_imports
    tree = ast.parse(contents)
  File "/usr/local/anaconda3/envs/learn_pytorch/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 29
    print "Generate Fonts"
```

**Comment by alan-barzilay** [comment]
Hello, I know this is an old issue, but if anyone could provide a minimum setup to reproduce this errors I would appreciate it. At the moment I can't seem to reproduce it in my machine and all python3 travis tests are passing.
As the new maintainer of this project, in the coming weeks I intend to drop support for python 2 and refactor some parts of the code base that are python2 related. I would like to also look into this issue, but at the moment I can't seem to replicate this error

**Comment by abhiksark** [comment]
Sorry @alan-barzilay don't recollect what i was doing.

**Comment by alan-barzilay** [comment]
since PR #255 has dropped python 2 and no one seems to be able to present a minimal setup to reproduce this error, I'm going to consider it solved. Feel free to reopen the issue if it persists and you can provide a minimum setup to reproduce it
