### ISSUE TITLE
apache-airflow missing from mapping

### ISSUE THREAD

**Issue by brentfollin** [bndr/pipreqs#179]
For packages that import airflow, e.g.

```
Collecting airflow==0.6
  Downloading https://files.pythonhosted.org/packages/98/e7/d8cad667296e49a74d64e0a55713fcd491301a2e2e0e82b94b065fda3087/airflow-0.6.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/envs/cortex/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-596i9f46/airflow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-596i9f46/airflow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-596i9f46/airflow/pip-egg-info
         cwd: /tmp/pip-install-596i9f46/airflow/
    Complete output (13 lines):
    running egg_info
    creating /tmp/pip-install-596i9f46/airflow/pip-egg-info/airflow.egg-info
    writing /tmp/pip-install-596i9f46/airflow/pip-egg-info/airflow.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-install-596i9f46/airflow/pip-egg-info/airflow.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-install-596i9f46/airflow/pip-egg-info/airflow.egg-info/top_level.txt
    writing manifest file '/tmp/pip-install-596i9f46/airflow/pip-egg-info/airflow.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-install-596i9f46/airflow/pip-egg-info/airflow.egg-info/SOURCES.txt'
    writing manifest file '/tmp/pip-install-596i9f46/airflow/pip-egg-info/airflow.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-596i9f46/airflow/setup.py", line 32, in <module>
        raise RuntimeError('Please install package apache-airflow instead of airflow')
    RuntimeError: Please install package apache-airflow instead of airflow
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by mmngreco** [comment]
Yes, I've also address this issue and I'm wondering  if another packages could be missed too.

## MRE

```bash
mkdir pkg
echo "from airflow.decorators import task" >> pkg/main.py
pipreqs pkg
cat ./pkg/requirements.txt
# airflow==0.6
```
