### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by keepwonder** [bndr/pipreqs#182]
ERROR: Failed on file: .\src\action\browser.py
Traceback (most recent call last):
  File "e:\installed_programs\continuum\anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "e:\installed_programs\continuum\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "E:\installed_programs\Continuum\Anaconda2\Scripts\pipreqs.exe\__main__.py", line 9, in <module>
  File "e:\installed_programs\continuum\anaconda2\lib\site-packages\pipreqs\pipreqs.py", line 396, in main
    init(args)
  File "e:\installed_programs\continuum\anaconda2\lib\site-packages\pipreqs\pipreqs.py", line 341, in init
    extra_ignore_dirs=extra_ignore_dirs)
  File "e:\installed_programs\continuum\anaconda2\lib\site-packages\pipreqs\pipreqs.py", line 91, in get_all_imports
    raise exc
  File "<unknown>", line 308
    record2json(os.path.join(config.biil_info_dir/today, f'{self.title}.json'), info=data, day=today)
                                                                            ^
SyntaxError: invalid syntax

**Comment by jonafato** [comment]
Is your `pipreqs` installed into a Python environment that doesn't support f-strings? Based on that stack trace, it looks like it's failing on an f-string, so making sure that your `pipreqs` install is using the same version of Python as your project should address the issue.

**Comment by keepwonder** [comment]
I installed pipreqs in the same envireoment the python I use, and then I got this error:

F:\dev\DaiJi (master -> origin)                                                                      
(DaiJi) λ which python                                                                               
/e/Envs/DaiJi/Scripts/python                                                                         
                                                                                                     
F:\dev\DaiJi (master -> origin)                                                                      
(DaiJi) λ which pipreqs                                                                              
/e/Envs/DaiJi/Scripts/pipreqs                                                                        
                                                                                                     
F:\dev\DaiJi (master -> origin)                                                                      
(DaiJi) λ pipreqs.exe .                                                                              
Traceback (most recent call last):                                                                   
  File "E:\installed_programs\Continuum\Anaconda3\Lib\runpy.py", line 193, in _run_module_as_main    
    "__main__", mod_spec)                                                                            
  File "E:\installed_programs\Continuum\Anaconda3\Lib\runpy.py", line 85, in _run_code               
    exec(code, run_globals)                                                                          
  File "E:\Envs\DaiJi\Scripts\pipreqs.exe\__main__.py", line 7, in <module>                          
  File "e:\envs\daiji\lib\site-packages\pipreqs\pipreqs.py", line 470, in main                       
    init(args)                                                                                       
  File "e:\envs\daiji\lib\site-packages\pipreqs\pipreqs.py", line 409, in init                       
    follow_links=follow_links)                                                                       
  File "e:\envs\daiji\lib\site-packages\pipreqs\pipreqs.py", line 122, in get_all_imports            
    contents = f.read()                                                                              
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 370: illegal multibyte sequence
