### ISSUE TITLE
python3 invalid syntax

### ISSUE THREAD

**Issue by LianGee** [bndr/pipreqs#194]
```
  File "<unknown>", line 54
    def error_handler(exception: Exception):
                               ^
SyntaxError: invalid syntax
```

**Comment by BiteFoo** [comment]
same issues :(

**Comment by mhetrerajat** [comment]
Can you please provide more details about the issue i.e how can I reproduce it ?

**Comment by jonafato** [comment]
This kind of error tends to happen when you have `pipreqs` installed in a Python 2 environment and try to run it on Python 3 code. Can you make sure `pipreqs` is installed in the same environment you expect your code to run in?

**Comment by LianGee** [comment]
> @LianGee @BiteFoo
> Can you please provide more details about the issue i.e how can I reproduce it?

I just run `pipreqs ./` on my python3 flask application.
And the error occurred on blow:
```python
@app.errorhandler(Exception)
def error_handler(exception: Exception):
    if exception:
        log.error(traceback.format_exc())
        return Response.failed(msg=f'{exception}')
```

```
➜  epidemic git:(master) ✗ pip3 list|grep pipreqs
pipreqs                0.4.10   
➜  epidemic git:(master) ✗ pipreqs ./
ERROR: Failed on file: ./app.py
Traceback (most recent call last):
  File "/usr/local/bin/pipreqs", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 470, in main
    init(args)
  File "/usr/local/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 409, in init
    follow_links=follow_links)
  File "/usr/local/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 138, in get_all_imports
    raise exc
  File "<unknown>", line 47
    def error_handler(exception: Exception):
                               ^
SyntaxError: invalid syntax
```

**Comment by LianGee** [comment]
@jonafato 
```
➜  epidemic git:(master) ✗ pip list|grep pipreqs
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
pipreqs             0.4.10     
➜  epidemic git:(master) ✗ pip3 list|grep pipreqs
pipreqs                0.4.10   
```
I did installed it on both python2 and python3.

**Comment by jonafato** [comment]
@LianGee This is ultimately a path issue. You could uninstall the Python 2 version or modify your path so that your Python 3 version comes first. The best route is to uninstall both and something like [`virtualenv`](https://virtualenv.pypa.io/en/stable/), [`venv`](https://docs.python.org/3/library/venv.html), etc. to manage your Python environments, keeping your tools installed in a per-project basis.

**Comment by LianGee** [comment]
@jonafato  Thanks a lot. It does work.
