### ISSUE TITLE
ERROR: Failed on file: ./<filename>.py

### ISSUE THREAD

**Issue by modernpacifist** [bndr/pipreqs#197]
ERROR: Failed on file: ./<filename>.py
Traceback (most recent call last):
   File "/home/<myuser>/.local/bin/pipreqs", line 10, in <module>
       sys.exit(main())
     File "/home/<myuser>/.local/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 470, in main
       init(args)
     File "/home/<myuser>/.local/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 409, in init
       follow_links=follow_links)
     File "/home/<myuser>/.local/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 138, in get_all_imports
       raise exc
     File "<unknown>", line 7
       return f"<string>#"
                                ^
SyntaxError: invalid syntax

P.S.
    **Formatted** string containing ' #" ' symbol combination, this error occurs.

**Comment by jonafato** [comment]
Your `pipreqs` is installed in a Python 2.7 environment, but f-strings are a Python 3-only feature. Please install `pipreqs` using the same version of Python your code targets, ideally in a virtual environment.

**Comment by modernpacifist** [comment]
@jonafato strange, that I did not thought about it.
Case closed.
