### ISSUE TITLE
SyntaxError: invalid syntax in lambda function

### ISSUE THREAD

**Issue by MSVO** [bndr/pipreqs#198]
## Steps to recreate error:  
- Install pipreqs ```sudo pip install pipreqs```
- Use pipreqs ```pipreqs fosscell-django/```
> fosscell-django is my virtualenv project directory and virtualenv is not active in any step

## Error log
```
ERROR: Failed on file: fosscell-django/lib/python3.8/site-packages/openid/urinorm.py
Traceback (most recent call last):
  File "/usr/bin/pipreqs", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/pipreqs/pipreqs.py", line 470, in main
    init(args)
  File "/usr/lib/python3.8/site-packages/pipreqs/pipreqs.py", line 406, in init
    candidates = get_all_imports(input_path,
  File "/usr/lib/python3.8/site-packages/pipreqs/pipreqs.py", line 138, in get_all_imports
    raise exc
  File "/usr/lib/python3.8/site-packages/pipreqs/pipreqs.py", line 124, in get_all_imports
    tree = ast.parse(contents)
  File "/usr/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 76
    map(lambda (m, n): u'%s-%s' % (unichr(m), unichr(n)),
               ^
SyntaxError: invalid syntax
```

**Comment by jonafato** [comment]
`lambda (m, n):` is not valid Python 3 syntax; this feature was removed in [PEP 3113](https://www.python.org/dev/peps/pep-3113/). Please be sure `pipreqs` is installed into the same environment your code is targeting.

**Comment by jonafato** [comment]
Closing this as a version mismatch issue. If you find that it's reproducible with pipreqs installed to the same environment as your code targets, please update with more details here to reopen.

**Comment by MSVO** [comment]
The same error is reproduced with pipreqs installed to the same environment as my code.  
The following describes steps I did this time.   
1. start virtualenv
```
[salih@apparel fosscell-django]$ source bin/activate
```
2. reinstall pipreqs
```
(fosscell-django) [salih@apparel fosscell-django]$ pip uninstall pipreqs
Found existing installation: pipreqs 0.4.10
Uninstalling pipreqs-0.4.10:
  Would remove:
    /home/salih/Work/fosscell-django/bin/pipreqs
    /home/salih/Work/fosscell-django/lib/python3.8/site-packages/pipreqs-0.4.10.dist-info/*
    /home/salih/Work/fosscell-django/lib/python3.8/site-packages/pipreqs/*
Proceed (y/n)? y
  Successfully uninstalled pipreqs-0.4.10
(fosscell-django) [salih@apparel fosscell-django]$ pip --version
pip 20.0.2 from /home/salih/Work/fosscell-django/lib/python3.8/site-packages/pip (python 3.8)
(fosscell-django) [salih@apparel fosscell-django]$ pip install pipreqs
Collecting pipreqs
  Using cached pipreqs-0.4.10-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: yarg in ./lib/python3.8/site-packages (from pipreqs) (0.1.9)
Requirement already satisfied: docopt in ./lib/python3.8/site-packages (from pipreqs) (0.6.2)
Requirement already satisfied: requests in ./lib/python3.8/site-packages (from yarg->pipreqs) (2.23.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./lib/python3.8/site-packages (from requests->yarg->pipreqs) (1.25.8)
Requirement already satisfied: chardet<4,>=3.0.2 in ./lib/python3.8/site-packages (from requests->yarg->pipreqs) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in ./lib/python3.8/site-packages (from requests->yarg->pipreqs) (2.9)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.8/site-packages (from requests->yarg->pipreqs) (2019.11.28)
Installing collected packages: pipreqs
Successfully installed pipreqs-0.4.10
``` 
3. check pip and python version
```
(fosscell-django) [salih@apparel fosscell-django]$ pipreqs --version
0.4.10
(fosscell-django) [salih@apparel fosscell-django]$ python --version
Python 3.8.1
```
4. run pipreqs. The console input and output is attached below
```
(fosscell-django) [salih@apparel fosscell-django]$ pipreqs .
ERROR: Failed on file: ./lib/python3.8/site-packages/openid/urinorm.py
Traceback (most recent call last):
  File "/home/salih/Work/fosscell-django/bin/pipreqs", line 8, in <module>
    sys.exit(main())
  File "/home/salih/Work/fosscell-django/lib/python3.8/site-packages/pipreqs/pipreqs.py", line 470, in main
    init(args)
  File "/home/salih/Work/fosscell-django/lib/python3.8/site-packages/pipreqs/pipreqs.py", line 406, in init
    candidates = get_all_imports(input_path,
  File "/home/salih/Work/fosscell-django/lib/python3.8/site-packages/pipreqs/pipreqs.py", line 138, in get_all_imports
    raise exc
  File "/home/salih/Work/fosscell-django/lib/python3.8/site-packages/pipreqs/pipreqs.py", line 124, in get_all_imports
    tree = ast.parse(contents)
  File "/usr/lib64/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 76
    map(lambda (m, n): u'%s-%s' % (unichr(m), unichr(n)),
               ^
SyntaxError: invalid syntax
(fosscell-django) [salih@apparel fosscell-django]$
```

**Comment by jonafato** [comment]
I see now. I missed that this was a third-party package at first. I suspect that this code is not imported by your django project and wouldn't work if it was. The line in question is https://github.com/openid/python-openid/blob/f7e13536f0d1828d3cef5ae7a7b55cabadff37fc/openid/urinorm.py#L76. Per the [Requirements section of the README](https://github.com/openid/python-openid/tree/f7e13536f0d1828d3cef5ae7a7b55cabadff37fc#requirements), python-openid is Python 2 only. I see some issues referencing https://github.com/necaris/python3-openid as an alternative, but I don't use either library and can't speak to that personally. I'd recommend removing that library from your project, but if you'd simply like to ignore that directory, you can use the `--ignore` flag with `pipreqs`.

**Comment by MSVO** [comment]
That solved it. Thank you @jonafato . I uninstalled python-openid which was unused in my Python 3 project.
