### ISSUE TITLE
Error while creating requirements.txt

### ISSUE THREAD

**Issue by gil9red** [bndr/pipreqs#23]
Hello!

```
C:\Users\ipetrash\Desktop\PyScripts\hideme.ru-proxy-list>pipreqs C:\Users\ipetrash\Desktop\PyScripts\hideme.ru-proxy-list
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\pipreqs.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\pipreqs\pipreqs.py", line 178, in main
    init(args)
  File "C:\Python34\lib\site-packages\pipreqs\pipreqs.py", line 157, in init
    local = get_import_local(candidates)
  File "C:\Python34\lib\site-packages\pipreqs\pipreqs.py", line 112, in get_import_local
    local = get_locally_installed_packages()
  File "C:\Python34\lib\site-packages\pipreqs\pipreqs.py", line 105, in get_locally_installed_packages
    'version': package[1].replace(".dist", ""),
IndexError: list index out of range
```

Used for: https://github.com/gil9red/hideme.ru-proxy-list

Sincerely yours,
gil9red

**Comment by gil9red** [comment]
Windows 7, 64

**Comment by bofm** [comment]
Windows 10 x64, Python 3.5 x64. The same bug.

**Comment by littmus** [comment]
@bofm It works well in my pc, win10 x64, python 3.4 x32.
Can you give a log run with `pipreqs --debug`?

**Comment by gil9red** [comment]
```
C:\>pipreqs C:\Users\ipetrash\Desktop\PyScripts\moswar_bot
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\pipreqs.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\pipreqs\pipreqs.py", line 215, in main
    init(args)
  File "C:\Python34\lib\site-packages\pipreqs\pipreqs.py", line 173, in init
    candidates = get_all_imports(args['<path>'], encoding=encoding)
  File "C:\Python34\lib\site-packages\pipreqs\pipreqs.py", line 58, in get_all_imports
    for line in lines:
  File "C:\Python34\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 4268: character maps to <undefined>
```

```
C:\>pipreqs --encoding=utf8 --debug  C:\Users\ipetrash\Desktop\PyScripts\moswar_bot
DEBUG: Found packages: {'random', 'cx_Freeze', 'time', 'sys', 'urllib', 'logging', 'PySide', 'datetime'}
DEBUG: Found imports: PySide, cx_Freeze
DEBUG: Getting packages information from Local/PyPI
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\pipreqs.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\pipreqs\pipreqs.py", line 215, in main
    init(args)
  File "C:\Python34\lib\site-packages\pipreqs\pipreqs.py", line 190, in init
    local = get_import_local(candidates, encoding=encoding)
  File "C:\Python34\lib\site-packages\pipreqs\pipreqs.py", line 137, in get_import_local
    local = get_locally_installed_packages()
  File "C:\Python34\lib\site-packages\pipreqs\pipreqs.py", line 130, in get_locally_installed_packages
    'version': package[1].replace(".dist", ""),
IndexError: list index out of range

```

**Comment by littmus** [comment]
I tested `get_locally_installed_packages` alone and same problem occurred.
This problem occurs because `sys.path` populated differently in py2 and py3.
```
C:\Users\dongwon>python -c "import sys; print(sys.path)"
['', 'C:\\WINDOWS\\SYSTEM32\\python27.zip', 'C:\\Python27\\DLLs', 'C:\\Python27\\lib', 'C:\\Python27\\lib\\plat-win', 'C:\\Python27\\lib\\lib-tk', 'C:\\Python27', 'C:\\Python27\\lib\\site-packages']

C:\Users\dongwon>python3 -c "import sys; print(sys.path)"
['', 'C:\\Python34\\lib\\site-packages\\mps_youtube-0.2.5-py3.4.egg', 'C:\\Python34\\lib\\site-packages\\pafy-0.3.74-py3.4.egg', 'C:\\Python34\\lib\\site-packages\\pyforms-0.1.3-py3.4.egg', 'C:\\Python34\\lib\\site-packages\\numpy-1.10.1-py3.4-win32.egg', 'C:\\Python34\\lib\\site-packages\\visvis-1.9.2-py3.4.egg', 'C:\\Python34\\lib\\site-packages\\pyopengl-3.1.1a1-py3.4.egg', 'C:\\WINDOWS\\SYSTEM32\\python34.zip', 'C:\\Python34\\Lib', 'C:\\Python34\\DLLs', 'C:\\Users\\dongwon', 'C:\\Windows', 'C:\\Python34', 'C:\\Python34\\lib\\site-packages']
```

**Comment by bndr** [comment]
I can't really debug this as I don't have a windows machine. Anyone willing to fix this bug, I will much appreciate it.

**Comment by rmallermartins** [comment]
Same here!

Ubuntu 14.04, Python 3.4

Using **pipreqs** installed under a **virtualenv**. It was working before (like last week) and now it just stopped with the same error:

```
(my-virtualenv) rodrigo@rodrigo-notebook:~/workspace/django$ pipreqs --debug MyProject/
DEBUG: Found packages: {'sys', 'django', 'material', '__future__', 'os'}
DEBUG: Found imports: Django, material
DEBUG: Getting packages information from Local/PyPI
qTraceback (most recent call last):
  File "/usr/local/bin/pipreqs", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/pipreqs/pipreqs.py", line 253, in main
    init(args)
  File "/usr/local/lib/python3.4/dist-packages/pipreqs/pipreqs.py", line 228, in init
    local = get_import_local(candidates, encoding=encoding)
  File "/usr/local/lib/python3.4/dist-packages/pipreqs/pipreqs.py", line 167, in get_import_local
    local = get_locally_installed_packages()
  File "/usr/local/lib/python3.4/dist-packages/pipreqs/pipreqs.py", line 160, in get_locally_installed_packages
    'version': package[1].replace(".dist", "").replace(".egg",""),
IndexError: list index out of range
```

**Comment by sebastiaopf** [comment]
Same issue for me in Linux Mint 17.
Some debug info:

`$ cat /etc/*issue*
Linux Mint 17 Qiana \n \l
Ubuntu 14.04.4 LTS \n \l

Linux Mint 17 QianaUbuntu 14.04.4 LTS`

`$ pipreqs --version
0.4.3
`

`$ pipreqs --debug ~/Documents/scripts/
DEBUG: Found packages: set(['__future__', 'bs4', 'functools', 'datetime', 'contextlib', 'tldextract', 'io', 'xml', 'IPy', 'whois', 'urllib', 're', 'json', 'pandas', 'math', 'string', 'urllib2', 'sys', 'jinja2', 'subprocess', 'socket', 'signal', 'urlparse', 'itertools', 'time', 'os', 'multiprocessing'])
DEBUG: Found imports: IPy, beautifulsoup4, Jinja2, pandas, tldextract, whois
DEBUG: Getting packages information from Local/PyPI
Traceback (most recent call last):
  File "/usr/local/bin/pipreqs", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pipreqs/pipreqs.py", line 253, in main
    init(args)
  File "/usr/local/lib/python2.7/dist-packages/pipreqs/pipreqs.py", line 228, in init
    local = get_import_local(candidates, encoding=encoding)
  File "/usr/local/lib/python2.7/dist-packages/pipreqs/pipreqs.py", line 167, in get_import_local
    local = get_locally_installed_packages()
  File "/usr/local/lib/python2.7/dist-packages/pipreqs/pipreqs.py", line 160, in get_locally_installed_packages
    'version': package[1].replace(".dist", "").replace(".egg",""),`

@gil9red fix works for me. Patch below:

`--- /usr/local/lib/python2.7/dist-packages/pipreqs/pipreqs.py.orig	2016-07-01 20:16:02.733618490 -0300
+++ /usr/local/lib/python2.7/dist-packages/pipreqs/pipreqs.py	2016-07-01 20:16:37.617619915 -0300
@@ -157,7 +157,7 @@
                             if ((i_item not in ignore) and
                                     (package[0] not in ignore)):
                                 packages[i_item] = {
-                                    'version': package[1].replace(".dist", "").replace(".egg",""),
+                                    'version': package[1].replace(".dist", "") if len(package) > 1 else None,
                                     'name': package[0]
                                 }
     return packages
`

**Comment by klvbdmh** [comment]
Any chance the above patch will be merged?

**Comment by bndr** [comment]
I thought this was fixed, does it not work in 0.4.4?

**Comment by jimanvlad** [comment]
I get this error as well on Windows 7 32 bit. Any fix?

**Comment by bndr** [comment]
Can you post your stacktrace and your version number

**Comment by jimanvlad** [comment]
```
(venv3) P:\TS Projects\Document Classification>pipreqs "P:\TS Projects\Document
Classification" --savepath reqs.txt
Traceback (most recent call last):
  File "P:\TS Projects\Python\python3\Lib\runpy.py", line 170, in _run_module_as
_main
    "__main__", mod_spec)
  File "P:\TS Projects\Python\python3\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "P:\TSPROJ~1\Python\venv3\Scripts\pipreqs.exe\__main__.py", line 9, in <m
odule>
  File "p:\tsproj~1\python\venv3\lib\site-packages\pipreqs\pipreqs.py", line 271
, in main
    init(args)
  File "p:\tsproj~1\python\venv3\lib\site-packages\pipreqs\pipreqs.py", line 225
, in init
    extra_ignore_dirs = extra_ignore_dirs)
  File "p:\tsproj~1\python\venv3\lib\site-packages\pipreqs\pipreqs.py", line 70,
 in get_all_imports
    contents = f.read()
  File "p:\tsproj~1\python\venv3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 121784: c
haracter maps to <undefined>
```

The fix above worked got me around the error (but the list of requirements that was created it completely bonkers).

**Comment by bndr** [comment]
Can you post the generated requirements.txt? Can you try with --encoding=utf-8 options, and see if the error persists

**Comment by jimanvlad** [comment]
--encoding=utf-8 worked. I'm still reviewing the .txt, I think it's actually correct.

**Comment by kasper747** [comment]
For others who might have similar problem. utf-8 have not worked for me, but with iso-8859-1 it worked:
` pipreqs --encoding=iso-8859-1 ./`

**Comment by hassanbest** [comment]
@kasper747  Thanks your solution worked

**Comment by Lukkar90** [comment]
@kasper747 Thanks! It works splendidly

**Comment by bsurd** [comment]
> For others who might have similar problem. utf-8 have not worked for me, but with iso-8859-1 it worked:
> ` pipreqs --encoding=iso-8859-1 ./`

Well, this command works but sadly it's not generating the requirements.txt file correctly if you're using a venv.

**Comment by soumya997** [comment]
@bndr I don't know, but **it's taking forever** in my windows machine to generate the requirements.txt file.
When I installed the package, it was showing this 
<br>
<img src = "https://i.imgur.com/nvRta0I.png">
so I changed the path from there to this one `C:\Users\USER\AppData\Local\Programs\Python\Python37\Scripts` because it was showing `pipreq command is not recognized`.but still its taking so much time, after 20-30 min when I stop that using "ctrl+c" it throws this error.
PS: (I got this path using the $PATH command),o/p of this command was this->
```
PATH=D:\Users\USER\Anaconda3;D:\Users\USER\Anaconda3\Library\mingw-w64\bin;D:\Users\USER\Anaconda3\Library\usr\bin;D:\Users\USER\Anaconda3\Library\bin;D:\Users\USER\Anaconda3\Scripts;D:\Users\USER\Anaconda3\bin;D:\Users\USER\Anaconda3\condabin;C:\Python38\Scripts;C:\Python38;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Python27\python.exe;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files (x86)\MATLAB\R2009a\bin;C:\Program Files (x86)\MATLAB\R2009a\bin\win32;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files\PuTTY;C:\Program Files\MySQL\MySQL Shell 8.0\bin;C:\Users\USER\AppData\Local\Programs\Python\Python37\Scripts;C:\Users\USER\AppData\Local\Programs\Python\Python37;C:\Users\USER\AppData\Local\Microsoft\WindowsApps;C:\Users\USER\AppData\Local\Programs\Microsoft VS Code\bin;C:\MinGW\bin;C:\Users\USER\AppData\Roaming\npm;C:\Program Files\Docker Toolbox;C:\Program Files\MongoDB\Server\4.4\bin;C:\Program Files\heroku\bin

```
I have windows 10 x 64.
Any solution?
I used `pipreqs D:\Documents\My_projects\static\resume_st.py` to generate the requirements.txt file. it was taking so much to to do that,so I stoped it using "ctrl+c",Then this error happened,this is the Traceback-> 
```
(base) D:\Documents\My_projects\static>pipreqs D:\Documents\My_projects\static\resume_st.py
Traceback (most recent call last):
  File "d:\users\user\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\users\user\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\Scripts\pipreqs.exe\__main__.py", line 7, in <module>
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\pipreqs\pipreqs.py", line 470, in main
    init(args)
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\pipreqs\pipreqs.py", line 460, in init
    generate_requirements_file(path, imports)
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\pipreqs\pipreqs.py", line 165, in generate_requirements_file
    with _open(path, "w") as out_file:
  File "d:\users\user\anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\pipreqs\pipreqs.py", line 88, in _open
    file = open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Documents\\My_projects\\static\\resume_st.py\\requirements.txt'
```

**Comment by Auckland68** [comment]
> For others who might have similar problem. utf-8 have not worked for me, but with iso-8859-1 it worked:
> ` pipreqs --encoding=iso-8859-1 ./`

After two days of trying to fix this and getting frustrated it worked. Thank you!!

**Comment by mingjun1120** [comment]
Hi, I am currently using `pipreqs --version` 0.4.10 in my Windows. I have tried many ways to create a requirement.txt in my **project folder namely Streamlit Project** file but it keeps failing. 

`pipreqs --encoding=iso-8859-1 ./` This method doesn't work for me because I am using a .venv for my project (VSCode).
`pipreqs --encoding=utf8 ./` This also doesn't work.

```
C:\Users\Jun\Desktop\Streamlit Project>pipreqs ./
Traceback (most recent call last):
  File "c:\users\jun\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jun\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jun\anaconda3\Scripts\pipreqs.exe\__main__.py", line 7, in <module>
  File "c:\users\jun\anaconda3\lib\site-packages\pipreqs\pipreqs.py", line 470, in main
    init(args)
  File "c:\users\jun\anaconda3\lib\site-packages\pipreqs\pipreqs.py", line 406, in init
    candidates = get_all_imports(input_path,
  File "c:\users\jun\anaconda3\lib\site-packages\pipreqs\pipreqs.py", line 122, in get_all_imports
    contents = f.read()
  File "c:\users\jun\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 263042: character maps to <undefined>
```
```
C:\Users\Jun\Desktop\Streamlit Project>pipreqs --encoding=utf8 ./
Traceback (most recent call last):
  File "c:\users\jun\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jun\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jun\anaconda3\Scripts\pipreqs.exe\__main__.py", line 7, in <module>
  File "c:\users\jun\anaconda3\lib\site-packages\pipreqs\pipreqs.py", line 470, in main
    init(args)
  File "c:\users\jun\anaconda3\lib\site-packages\pipreqs\pipreqs.py", line 406, in init
    candidates = get_all_imports(input_path,
  File "c:\users\jun\anaconda3\lib\site-packages\pipreqs\pipreqs.py", line 122, in get_all_imports
    contents = f.read()
  File "c:\users\jun\anaconda3\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 81: invalid start byte
```

**Comment by Nishith-Savla** [comment]
This seems to have worked for me
`pipreqs --encoding=utf-8-sig ./`
