### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8c in position 358: illegal multibyte sequence

### ISSUE THREAD

**Issue by wellitecho** [bndr/pipreqs#241]
# What happened
I used pipreqs to freeze package requirements for one of my projects by running 'pipreqs' in the project directory, but it caused this error: UnicodeDecodeError: 'gbk' codec can't decode byte 0x8c in position 358: illegal multibyte sequence.

# What I expected
It should work without causing any problem.

# Full traceback
Traceback (most recent call last):
  File "c:\users\myAccount\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\myAccount\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\myAccount\anaconda3\Scripts\pipreqs.exe\__main__.py", line 7, in <module>
  File "c:\users\myAccount\anaconda3\lib\site-packages\pipreqs\pipreqs.py", line 470, in main
    init(args)
  File "c:\users\myAccount\anaconda3\lib\site-packages\pipreqs\pipreqs.py", line 406, in init
    candidates = get_all_imports(input_path,
  File "c:\users\myAccount\anaconda3\lib\site-packages\pipreqs\pipreqs.py", line 122, in get_all_imports
    contents = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8c in position 358: illegal multibyte sequence

# What I did then
I went to c:\users\myAccount\anaconda3\lib\site-packages\pipreqs\pipreqs.py and modified lines near line 122(contents = f.read()), namely, the lines concerning file encoding:
original:
```python
                with open_func(file_name, "r", encoding=encoding) as f:
                    contents = f.read()

```
after adding try/except:
```python
            try:
                with open_func(file_name, "r", encoding=encoding) as f:
                    contents = f.read()
            except:
                with open_func(file_name, "r", encoding='utf-8') as f:
                    contents = f.read()
```
Then it worked without problems. Albeit a temp fix.

# What need to be done
The assumption about the encoding of the source code file need to be revised?

**Comment by wellitecho** [comment]
#214 
Maybe we should dynamically decide what the encoding of the file is?

**Comment by alan-barzilay** [comment]
I think revisiting the encoding option is a good idea as well, I think I will make utf-8 the default since (if I'm not mistaking) it is the default encoding for python3.
@wellitecho Could you provide a minimal setup to reproduce your error? I want to add something similar in our tests to prevent it from happening again

**Comment by wellitecho** [comment]
a minimal setup to reproduce the error:
```python
import pysnooper

"""
长注释

this comment with Chinese characters caused the UnicodeDecodeError, I believe.
the error reads: 'gbk' codec can't decode byte 0xaf in position 606: illegal multibyte sequence

note:
you need to put this in a .py file, and save the file with utf-8 encoding
"""
```

Also, I read somewhere else that setting the open_func's encoding to 'utf-8' will resolve such issues. It's also my case. But I don't know how good it is in other cases.

**Comment by alan-barzilay** [comment]
@wellitecho thank you for your detailed response!
I will try to address this issue in the next release of pipreqs, I will update this thread once I have any updates

**Comment by alan-barzilay** [comment]
@wellitecho, quick question, you were using python3, right?
Also, when you run python in your command line, your environment defaults it to python 2 or 3?
I confirmed that the default encoding in python 3 is utf-8 (which was not the case in python2), I believe that somehow when you use pipreqs you are using python2 to run it because changing the encoding to utf-8 shouldn't make any difference whatsoever

**Comment by wellitecho** [comment]
@alan-barzilay I am using the Python bundled with the Anaconda distribution, which, as I checked now, is Python  version 3.8.5

**Comment by wellitecho** [comment]
@alan-barzilay there is no Python 2 installed in my OS; and the default encoding of my .py files is utf-8.
So as I mentioned, the bug arises when a utf-8 encoded .py file contains a block comment(surrounded by three double quotes) that has Chinese characters in it. And somehow pipreqs decides that this file is encoded in gbk, which is a common encoding for files with Chinese characters. But when pipreqs uses gbk to decode this file, it fails.

**Comment by alan-barzilay** [comment]
@wellitecho thank you for the clarification.
To mark pipreqs as an executable in unix systems, we have at the beginning of the file the line
`#!/usr/bin/env python`
This informs the system that it should execute the script using the python command. The problem is that on some older systems the python command is actually python2 instead of python3, so I though that you may have been unknowingly using python 2 to execute pipreqs. But if you don't even have it in your system I don't know what is happening.

If an encoding is never defined in pipreqs, it simply passes `None` as an encoding for the open function. When the open function receives `None` as an encoding (which is its default value) it assumes the file is using the utf-8 encoding as it is the default encoding for python 3 files. 

There is something in your system that is forcing the file to be opened as gbk encoded (my guess was python 2, but as you established that can't be it), I believe this is not an pipreqs issue.
I tried reproducing your error in 2 different machines and it worked as intended.

I will be closing this issue since I couldn't reproduce your error

**Comment by alan-barzilay** [comment]
Ok, I did some more reading and I found the following about the open function:
https://docs.python.org/3/library/functions.html?highlight=open#open
> encoding is the name of the encoding used to decode or encode the file. This should only be used in text mode. The default encoding is platform dependent (whatever locale.getpreferredencoding() returns), but any text encoding supported by Python can be used. See the codecs module for the list of supported encodings.

So, @wellitecho, my guess is that your region is defined as such that the default encoding used is gbk. I will make a commit that forces utf-8 as the default and this should solve all of our problems.
