### ISSUE TITLE
Please add/expose pip access through firewalls

### ISSUE THREAD

**Issue by GadgetSteve** [bndr/pipreqs#27]
Currently I cannot use pipreqs other than with locals settings as I am behind a poxy server, *spelling intentional*.

But pip allows working with --proxy= when using from the command line.

If this was exposed as a command line option then the flexibility would be there for pipreqs.

**Comment by bndr** [comment]
This should work in version 0.3.0, just pass --proxy with host in format ```user:password@proxyserver:port```, the argument is then passed down to the requests library http://docs.python-requests.org/en/v1.0.4/user/advanced/#proxies

Tell me if you got it working

**Comment by GadgetSteve** [comment]
Not behind the proxy now 20:15 and the poxy proxy is at work - I'll try to get a chance to try it tomorrow.

**Comment by GadgetSteve** [comment]
With 0.3.0 if I use:pipreqs --proxy our_proxy
'use:pipreqs --proxy our_proxy .` or 'use:pipreqs --proxy our_proxy filename.py` 
then I get an usage message:
    Usage:
        pipreqs [options] <path>
If I use `--proxy=our_proxy` then I get `--proxy must not have an argument`

I suspect that it is trying to read the proxy from an environment variable because if I use just --proxy then I get:

Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pipreqs.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\pipreqs\pipreqs.py", line 208, in main
    init(args)
  File "c:\python27\lib\site-packages\pipreqs\pipreqs.py", line 188, in init
    pypi_server=pypi_server)
  File "c:\python27\lib\site-packages\pipreqs\pipreqs.py", line 89, in get_impor
ts_info
    response = requests.get("{0}{1}/json".format(pypi_server, item), proxies=pro
xy)
  File "c:\python27\lib\site-packages\requests\api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "c:\python27\lib\site-packages\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 465, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "c:\python27\lib\site-packages\requests\adapters.py", line 337, in send
    conn = self.get_connection(request.url, proxies)
  File "c:\python27\lib\site-packages\requests\adapters.py", line 244, in get_co
nnection
    proxy = prepend_scheme_if_needed(proxy, 'http')
  File "c:\python27\lib\site-packages\requests\utils.py", line 652, in prepend_s
cheme_if_needed
    scheme, netloc, path, params, query, fragment = urlparse(url, new_scheme)
  File "c:\python27\lib\urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "c:\python27\lib\urlparse.py", line 182, in urlsplit
    i = url.find(':')
AttributeError: 'bool' object has no attribute 'find'

but --help does not mention which environment variable is used.

**Comment by bndr** [comment]
I clarified in --help that 
```
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"
```
environment variables are used. So if you set those env variables then they will automatically be passed down to the requests library

**Comment by GadgetSteve** [comment]
That should cover it nicely apart from one last question _shouldn't_ the HTTPS URL start with https - I am not sure but I would have expected them to?

**Comment by bndr** [comment]
Thanks. That's a good point, I will change it to https

**Comment by GadgetSteve** [comment]
Cheers - I will close this issue now on the basis that you have it in hand.
