### ISSUE TITLE
Error if script contains Umlauts (like ä,ö,ü)

### ISSUE THREAD

**Issue by sgaechter** [bndr/pipreqs#271]
pipreqs trows Error when script contains umlauts:
Stack trace:
```
ERROR: Failed on file: P:\PROJECTS\Dataplot_Preislistendownload\Dataplot_Preisliste.py
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\pipreqs.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\pipreqs\pipreqs.py", line 470, in main
    init(args)
  File "c:\python39\lib\site-packages\pipreqs\pipreqs.py", line 406, in init
    candidates = get_all_imports(input_path,
  File "c:\python39\lib\site-packages\pipreqs\pipreqs.py", line 138, in get_all_imports
    raise exc
  File "c:\python39\lib\site-packages\pipreqs\pipreqs.py", line 124, in get_all_imports
    tree = ast.parse(contents)
  File "c:\python39\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 89
    df = df.assign(WiederverkÃ¤ufer = round_col(vk - (vk /WVfaktor),2))
                              ^
```
attached affecting Script (please change to *.py :-) )
[Dataplot_Preislist.txt](https://github.com/bndr/pipreqs/files/7104757/Dataplot_Preislist.txt)

**Comment by sgaechter** [comment]
Hello @hasansezertasan probably it's a OS bug. From your post, I gather that you reproduced it with Linux. I use Windows. I will try to narrow it down even further.
