### ISSUE TITLE
get_locally_installed_packages() ignores some packages

### ISSUE THREAD

**Issue by hdformat** [bndr/pipreqs#29]
get_locally_installed_packages() ingnores the packages:

  - a package zipped
  - a package has the top_level.txt in EGG-INFO folder

Is there any reason for this?  it causes test_pipreqs.py failures. below is my environment

  - virtualenv site-packages

```
Directory of D:\projects\pipreqs\venv\Lib\site-packages

2015-10-20  오전 11:12    <DIR>          .
2015-10-20  오전 11:12    <DIR>          ..
2015-10-20  오전 11:00            22,394 docopt-0.6.2-py3.5.egg
2015-10-20  오전 11:01               286 easy-install.pth
2015-10-20  오전 11:06               126 easy_install.py
2015-10-20  오전 11:00    <DIR>          pip
2015-10-20  오전 11:00    <DIR>          pip-7.1.2.dist-info
2015-10-20  오전 11:00                22 pipreqs.egg-link
2015-10-20  오전 11:06    <DIR>          pkg_resources
2015-10-20  오전 11:01    <DIR>          requests-2.8.1-py3.5.egg
2015-10-20  오전 11:06    <DIR>          setuptools
2015-10-20  오전 11:06    <DIR>          setuptools-18.4.dist-info
2015-10-20  오전 11:12    <DIR>          wheel
2015-10-20  오전 11:12    <DIR>          wheel-0.23.0.dist-info
2015-10-20  오전 11:00            35,026 yarg-0.1.9-py3.5.egg
2015-10-20  오전 11:06    <DIR>          _markerlib
2015-10-20  오전 11:06    <DIR>          __pycache__
```

  - localy installed packages

```
Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)] on win32
>>> import wheel
>>> import _markerlib
>>> import easy_install
>>> import pkg_resources
>>> import setuptools
>>> import requests
>>> import pip
>>> import docopt
>>> import yarg
```

  - get_locally_installed_packages() returns (without requests, docopt, yarg)

```
{
'pip': {'name': 'pip', 'version': '7.1.2'}, 
'pipreqs': {'name': 'pipreqs.egg', 'version': 'info'}, 
'pkg_resources': {'name': 'setuptools', 'version': '18.4'}, 
'easy_install': {'name': 'setuptools', 'version': '18.4'}, 
'_markerlib': {'name': 'setuptools', 'version': '18.4'}, 
'setuptools': {'name': 'setuptools', 'version': '18.4'}, 
'numpy': {'name': 'numpy', 'version': '1.10.0b1'}, 
'wheel': {'name': 'wheel', 'version': '0.23.0'}
}
```

**Comment by bndr** [comment]
What happens when you run the tests in clean virtualenv? e.g
```
mkvirtualenv test_pipreqs
make test
```

can you post the output?

**Comment by hdformat** [comment]
I'm sorry,  I've tested in setting-up develop environment.  
as you commented, i did it in clean virtualenv, 

  - clone the repository
```
D:\projects>git clone https://github.com/bndr/pipreqs.git
Cloning into 'pipreqs'...
remote: Counting objects: 471, done.
emote: Total 471 (delta 0), reused 0 (delta 0), pack-reused 471R
Receiving objects: 100% (471/471), 92.91 KiB | 0 bytes/s, done.
Resolving deltas: 100% (258/258), done.
Checking connectivity... done.
```
  - set up the clean virtualenv
```
D:\projects>cd pipreqs
D:\projects\pipreqs>python -m venv venv
D:\projects\pipreqs>venv\Scripts\activate.bat
```

  - make test
```
(venv) D:\projects\pipreqs>make test
pip install -r requirements.txt
Collecting wheel==0.23.0 (from -r requirements.txt (line 1))
  Using cached wheel-0.23.0-py2.py3-none-any.whl
Collecting Yarg==0.1.9 (from -r requirements.txt (line 2))
  Using cached yarg-0.1.9-py2.py3-none-any.whl
Collecting docopt==0.6.2 (from -r requirements.txt (line 3))
Collecting requests (from Yarg==0.1.9->-r requirements.txt (line 2))
  Using cached requests-2.8.1-py2.py3-none-any.whl
Installing collected packages: wheel, requests, Yarg, docopt
Successfully installed Yarg-0.1.9 docopt-0.6.2 requests-2.8.1 wheel-0.23.0
python setup.py test
running test
running egg_info
creating pipreqs.egg-info
writing entry points to pipreqs.egg-info\entry_points.txt
writing top-level names to pipreqs.egg-info\top_level.txt
writing pipreqs.egg-info\PKG-INFO
writing requirements to pipreqs.egg-info\requires.txt
writing dependency_links to pipreqs.egg-info\dependency_links.txt
writing manifest file 'pipreqs.egg-info\SOURCES.txt'
reading manifest file 'pipreqs.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
warning: no files found matching 'stdlib' under directory 'docs'
warning: no files found matching 'mapping' under directory 'docs'
writing manifest file 'pipreqs.egg-info\SOURCES.txt'
running build_ext
test_custom_pypi_server (tests.test_pipreqs.TestPipreqs) ... ok
test_get_all_imports (tests.test_pipreqs.TestPipreqs) ... ok
test_get_import_name_without_alias (tests.test_pipreqs.TestPipreqs) ... ok
test_get_imports_info (tests.test_pipreqs.TestPipreqs) ... ok
test_get_use_local_only (tests.test_pipreqs.TestPipreqs) ... FAIL
test_init (tests.test_pipreqs.TestPipreqs) ... ok
test_init_local_only (tests.test_pipreqs.TestPipreqs) ... FAIL
test_init_overwrite (tests.test_pipreqs.TestPipreqs) ... WARNING:root:Requirements.txt already exists, use --force to overwrite it
ok
test_init_savepath (tests.test_pipreqs.TestPipreqs) ... ok

======================================================================
FAIL: test_get_use_local_only (tests.test_pipreqs.TestPipreqs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\projects\pipreqs\tests\test_pipreqs.py", line 58, in test_get_use_local_only
    self.assertTrue(item['name'].lower() in self.local)
AssertionError: False is not true

======================================================================
FAIL: test_init_local_only (tests.test_pipreqs.TestPipreqs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\projects\pipreqs\tests\test_pipreqs.py", line 77, in test_init_local_only
    self.assertTrue(item[0].lower() in self.local)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 9 tests in 21.901s

FAILED (failures=2)
make: *** [test] Error 1

(venv) D:\projects\pipreqs>
```

  - the error was occurred, i fixed line 114 of pipreqs.py like below
```
# package = root.split("/")[-1].split("-")
package = root.split(os.sep)[-1].split("-")
```

  - and all tests passed
```
(venv) D:\projects\pipreqs>make test
pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): wheel==0.23.0 in d:\projects\pipreqs\venv\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Yarg==0.1.9 in d:\projects\pipreqs\venv\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.2 in d:\projects\pipreqs\venv\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): requests in d:\projects\pipreqs\venv\lib\site-packages (from Yarg==0.1.9->-r requirements.txt (line 2))
python setup.py test
running test
running egg_info
writing dependency_links to pipreqs.egg-info\dependency_links.txt
writing requirements to pipreqs.egg-info\requires.txt
writing pipreqs.egg-info\PKG-INFO
writing top-level names to pipreqs.egg-info\top_level.txt
writing entry points to pipreqs.egg-info\entry_points.txt
reading manifest file 'pipreqs.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no files found matching 'stdlib' under directory 'docs'
warning: no files found matching 'mapping' under directory 'docs'
writing manifest file 'pipreqs.egg-info\SOURCES.txt'
running build_ext
test_custom_pypi_server (tests.test_pipreqs.TestPipreqs) ... ok
test_get_all_imports (tests.test_pipreqs.TestPipreqs) ... ok
test_get_import_name_without_alias (tests.test_pipreqs.TestPipreqs) ... ok
test_get_imports_info (tests.test_pipreqs.TestPipreqs) ... ok
test_get_use_local_only (tests.test_pipreqs.TestPipreqs) ... ok
test_init (tests.test_pipreqs.TestPipreqs) ... ok
test_init_local_only (tests.test_pipreqs.TestPipreqs) ... ok
test_init_overwrite (tests.test_pipreqs.TestPipreqs) ... WARNING:root:Requirements.txt already exists, use --force to overwrite it
ok
test_init_savepath (tests.test_pipreqs.TestPipreqs) ... ok

----------------------------------------------------------------------
Ran 9 tests in 20.133s

OK

(venv) D:\projects\pipreqs>
```

thanks
