### ISSUE TITLE
pipreqs invalid syntax

### ISSUE THREAD

**Issue by GigaHertzLegacy-SpiderX** [bndr/pipreqs#291]
What is the solution of this ?

```sh


ERROR: Failed on file: C:\Users\abira\OneDrive\Desktop\QuranSunnah\surah_setup.py
Traceback (most recent call last):
  File "C:\Users\abira\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\abira\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\abira\AppData\Local\Programs\Python\Python310\Scripts\pipreqs.exe\__main__.py", line 7, in <module>
  File "C:\Users\abira\AppData\Local\Programs\Python\Python310\lib\site-packages\pipreqs\pipreqs.py", line 488, in main
    init(args)
  File "C:\Users\abira\AppData\Local\Programs\Python\Python310\lib\site-packages\pipreqs\pipreqs.py", line 415, in init
    candidates = get_all_imports(input_path,
  File "C:\Users\abira\AppData\Local\Programs\Python\Python310\lib\site-packages\pipreqs\pipreqs.py", line 131, in get_all_imports
    raise exc
  File "C:\Users\abira\AppData\Local\Programs\Python\Python310\lib\site-packages\pipreqs\pipreqs.py", line 117, in get_all_imports
    tree = ast.parse(contents)
  File "C:\Users\abira\AppData\Local\Programs\Python\Python310\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 29
    if user_input1 == #here :
                      ^^^^^^^
SyntaxError: invalid syntax


```

**Comment by mingjun1120** [comment]
I found this solution from the CSDN forum (from China) but still, I don't know how to solve it even though I know Mandarin!
[](https://blog.csdn.net/Pragmatism_3568/article/details/105414950)
