### ISSUE TITLE
Error when trying to use 

### ISSUE THREAD

**Issue by rcyost** [bndr/pipreqs#301]
```$ pipreqs ./ --ignore .venv```

```
(python) C:\Users\yosty\Desktop\Desktop_Folder\14 - git\dataScripts\Text>pipreqs ./ --ignore .venv
ERROR: Failed on file: ./08_sentiment_analysis_with_bert-ry.py
Traceback (most recent call last):
  File "C:\Users\yosty\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yosty\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\yosty\Envs\python\Scripts\pipreqs.exe\__main__.py", line 7, in <module>
  File "c:\users\yosty\envs\python\lib\site-packages\pipreqs\pipreqs.py", line 488, in main
    init(args)
  File "c:\users\yosty\envs\python\lib\site-packages\pipreqs\pipreqs.py", line 415, in init
    candidates = get_all_imports(input_path,
  File "c:\users\yosty\envs\python\lib\site-packages\pipreqs\pipreqs.py", line 131, in get_all_imports
    raise exc
  File "c:\users\yosty\envs\python\lib\site-packages\pipreqs\pipreqs.py", line 117, in get_all_imports
    tree = ast.parse(contents)
  File "C:\Users\yosty\AppData\Local\Programs\Python\Python39\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 73
    !pip install -q -U watermark
    ^
SyntaxError: invalid syntax
```

Not sure how to troubleshoot as an unknown file is the reference? Any help would greatly be appreciated thank you.

**Comment by Tom-Teamo** [comment]
the same problem
