### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 454: character maps to <undefined>

### ISSUE THREAD

**Issue by CarlaFernandez** [bndr/pipreqs#321]
- **OS version**: Microsoft Windows 10 Pro, version 10.0.19044 compilation 19044
- **Local setup**: 
  - Python virtual environment with the following packages:
  ```
  atomicwrites==1.4.1
  attrs==22.1.0
  certifi==2022.6.15
  charset-normalizer==2.1.0
  chispa==0.9.2
  colorama==0.4.5
  docopt==0.6.2
  idna==3.3
  iniconfig==1.1.1
  joblib==1.1.0
  loguru==0.6.0
  numpy==1.23.1
  packaging==21.3
  pandas==1.4.3
  pipreqs==0.4.11
  plotly==5.9.0
  pluggy==1.0.0
  py==1.11.0
  py4j==0.10.9.5
  pyparsing==3.0.9
  pyspark==3.3.0
  pytest==7.1.2
  python-dateutil==2.8.2
  pytz==2022.1
  requests==2.28.1
  scikit-learn==1.1.2
  scipy==1.9.0
  six==1.16.0
  tenacity==8.0.1
  threadpoolctl==3.1.0
  tomli==2.0.1
  urllib3==1.26.11
  win32-setctime==1.1.0
  yarg==0.1.9
  ```
- **Detailed steps to reproduce the bug**: 
  - Execute `pipreqs project_name`

- **Full stacktrace**:
```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\carlafernandez\Documents\my_projects\project\project_name\venv-pyspark\Scripts\pipreqs.exe\__main__.py", line 7, in <module>
  File "C:\Users\carlafernandez\Documents\my_projects\project\project_name\venv-pyspark\lib\site-packages\pipreqs\pipreqs.py", line 488, in main
    init(args)
  File "C:\Users\carlafernandez\Documents\my_projects\project\project_name\venv-pyspark\lib\site-packages\pipreqs\pipreqs.py", line 415, in init
    candidates = get_all_imports(input_path,
  File "C:\Users\carlafernandez\Documents\my_projects\project\project_name\venv-pyspark\lib\site-packages\pipreqs\pipreqs.py", line 115, in get_all_imports
    contents = f.read()
  File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 454: character maps to <undefined>
```

**Comment by andrew-hossack** [comment]
Try again with:

`pipreqs --encoding=utf-8 project_name `

**Comment by Khalilsqu** [comment]
@andrew-hossack thanks, it worked
