### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 8033: character maps to <undefined>

### ISSUE THREAD

**Issue by frehburg** [bndr/pipreqs#376]
I encountered this error message when trying to use your package

(DeepECGI) C:\Users\Surface>pipreqs C:\Users\Surface\OneDrive\Documents\MATLAB\DeepECGImaging
Traceback (most recent call last):
  File "C:\Users\Surface\anaconda3\envs\DeepECGI\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Surface\anaconda3\envs\DeepECGI\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Surface\anaconda3\envs\DeepECGI\Scripts\pipreqs.exe\__main__.py", line 7, in <module>
  File "C:\Users\Surface\anaconda3\envs\DeepECGI\lib\site-packages\pipreqs\pipreqs.py", line 528, in main
    init(args)
  File "C:\Users\Surface\anaconda3\envs\DeepECGI\lib\site-packages\pipreqs\pipreqs.py", line 455, in init
    candidates = get_all_imports(input_path,
  File "C:\Users\Surface\anaconda3\envs\DeepECGI\lib\site-packages\pipreqs\pipreqs.py", line 115, in get_all_imports
    contents = f.read()
  File "C:\Users\Surface\anaconda3\envs\DeepECGI\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 8033: character maps to <undefined>

Python 3.8.16 

Windows 11

**Comment by ahmedoid** [comment]
Related https://github.com/bndr/pipreqs/issues/214
