### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 615: illegal multibyte sequence

### ISSUE THREAD

**Issue by danerlt** [bndr/pipreqs#387]
When I execute `pipreqs  myapp` command ,it tips error:
```
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\workspace\cube-studio\venv\Scripts\pipreqs.exe\__main__.py", line 7, in <module>
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\workspace\cube-studio\venv\Scripts\pipreqs.exe\__main__.py", line 7, in <module>
  File "D:\workspace\cube-studio\venv\lib\site-packages\pipreqs\pipreqs.py", line 528, in main
    init(args)
  File "D:\workspace\cube-studio\venv\lib\site-packages\pipreqs\pipreqs.py", line 455, in init
    candidates = get_all_imports(input_path,
  File "D:\workspace\cube-studio\venv\lib\site-packages\pipreqs\pipreqs.py", line 115, in get_all_imports
    contents = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 615: illegal multibyte sequence

```

**Comment by danerlt** [comment]
I think you can set the default encoding to utf-8.
