### ISSUE TITLE
Error executing newly installed pipreqs

### ISSUE THREAD

**Issue by satiani** [bndr/pipreqs#4]
I installed pipreqs using ```pip install pipreqs``` within my local virtualenv and then executed it, got this error:

```
~/code % pipreqs web
Looking for imports
Traceback (most recent call last):
  File "/home/satiani/code/web/venv/bin/pipreqs", line 8, in <module>
    load_entry_point('pipreqs==0.1.8', 'console_scripts', 'pipreqs')()
  File "/home/satiani/code/web/venv/local/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 109, in main
    init(args)
  File "/home/satiani/code/web/venv/local/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 92, in init
    imports = get_all_imports(args['<path>'])
  File "/home/satiani/code/web/venv/local/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 62, in get_all_imports
    with open(os.path.join(os.path.dirname(__file__), "stdlib"), "r") as f:
IOError: [Errno 2] No such file or directory: '/home/satiani/code/web/venv/local/lib/python2.7/site-packages/pipreqs/stdlib'
zsh: exit 1     pipreqs web
```

**Comment by bndr** [comment]
Strange, just tried it myself and it worked. 
```
virtualenv venv
source venv/bin/activate
pip install pipreqs
pipreqs /path/to/project
```

Can you explain in more detail? How did you create your virtualenv? What was in the project? Maybe try with new virtualenv?

**Comment by satiani** [comment]
Tried it on a completely new virtualenv, same result, see below:

```
~ % mkdir pipreqs_test
~ % cd pipreqs_test
Installing setuptools............done.
Installing pip...............done.
~/pipreqs_test % pip install pipreqs
Downloading/unpacking pipreqs
  Downloading pipreqs-0.1.8.tar.gz
  Running setup.py egg_info for package pipreqs

    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    warning: no files found matching 'stdlib' under directory 'docs'
Downloading/unpacking docopt (from pipreqs)
  Downloading docopt-0.6.2.tar.gz
  Running setup.py egg_info for package docopt

Downloading/unpacking yarg (from pipreqs)
  Downloading yarg-0.1.9.tar.gz
  Running setup.py egg_info for package yarg

Downloading/unpacking requests (from yarg->pipreqs)
  Downloading requests-2.6.2.tar.gz (451Kb): 451Kb downloaded
  Running setup.py egg_info for package requests

Installing collected packages: pipreqs, docopt, yarg, requests
  Running setup.py install for pipreqs

    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    warning: no files found matching 'stdlib' under directory 'docs'
  Running setup.py install for docopt

  Running setup.py install for yarg

  Running setup.py install for requests

Successfully installed pipreqs docopt yarg requests
Cleaning up...
~/pipreqs_test % pipreqs ~/code/web
Looking for imports
Traceback (most recent call last):
    load_entry_point('pipreqs==0.1.8', 'console_scripts', 'pipreqs')()
    init(args)
    imports = get_all_imports(args['<path>'])
    with open(os.path.join(os.path.dirname(__file__), "stdlib"), "r") as f:
zsh: exit 1     pipreqs ~/code/web
~/pipreqs_test % vi test.txt
~/pipreqs_test % python --version
Python 2.7.3
~/pipreqs_test % virtualenv --version
1.7.1.2
~/pipreqs_test %
```

**Comment by satiani** [comment]
my original comment accidentally missed some lines from the console, I edited and fixed it.

**Comment by bndr** [comment]
Hm.. this is definitely strange, thanks for reporting, I'll take a look into it.

**Comment by satiani** [comment]
No problem, let me know if you need more diagnostic output and I'll try to furnish it for you.

**Comment by dyzajash** [comment]
@satiani what version of virtualenv & pip you are using? 

On python 2.7.5, pip 6.0.8+ and venv  12.0.7 I have no problems. 

On python 2.7.5, pip 6.0.8+ and venv 10.X.X I have same issue as you. 

Maybe try to upgrade pip & virtualenv first? Also, have you python-dev packages? Request package sometimes fails if you don't have it.

**Comment by bndr** [comment]
@satiani Can you try it after upgrading virtualenv?

**Comment by nleite** [comment]
Got the same error. 
```shell 
Traceback (most recent call last):
  File "/usr/local/bin/pipreqs", line 9, in <module>
    load_entry_point('pipreqs==0.2.8', 'console_scripts', 'pipreqs')()
  File "/Library/Python/2.7/site-packages/pipreqs/pipreqs.py", line 178, in main
    init(args)
  File "/Library/Python/2.7/site-packages/pipreqs/pipreqs.py", line 147, in init
    candidates = get_all_imports(args['<path>'])
  File "/Library/Python/2.7/site-packages/pipreqs/pipreqs.py", line 55, in get_all_imports
    with open(join("stdlib"), "r") as f:
IOError: [Errno 2] No such file or directory: '/Library/Python/2.7/site-packages/pipreqs/stdlib'
```
I'm running on the lattes version of virtualenv and pip.

```shell
Darwin nair.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64

**Comment by underscorephil** [comment]
Same issue/symptoms here

**Comment by fr0der1c** [comment]
Same issue/symptoms here
