### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x84 in position 358: illegal multibyte sequence

### ISSUE THREAD

**Issue by DeweiWu** [bndr/pipreqs#410]
ing: urllib3 (1.26.12) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "C:\Users\68520\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\68520\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\68520\AppData\Local\Programs\Python\Python37\Scripts\pipreqs.exe\__main__.py", line 7, in <module>
    #
  File "C:\Users\68520\AppData\Local\Programs\Python\Python37\lib\site-packages\pipreqs\pipreqs.py", line 528, in main
    init(args)
  File "C:\Users\68520\AppData\Local\Programs\Python\Python37\lib\site-packages\pipreqs\pipreqs.py", line 458, in init
    follow_links=follow_links)
  File "C:\Users\68520\AppData\Local\Programs\Python\Python37\lib\site-packages\pipreqs\pipreqs.py", line 115, in get_all_imports
    contents = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x84 in position 358: illegal multibyte sequence

**Comment by alan-barzilay** [comment]
You have to figure out your file encoding to fix this issue, it is using a character not recognized by the default encoding. A good first attempt is to try utf-8
