### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by ArcTanSusan** [bndr/pipreqs#44]
```
> pipreqs powerdash
ERROR: Failed on file: powerdash/.tox/cover/lib/python2.7/site-packages/pylint/test/input/func_kwoa_py30.py
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/powerdash/bin/pipreqs", line 11, in <module>
    sys.exit(main())
  File "/home/vagrant/.virtualenvs/powerdash/local/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 253, in main
    init(args)
  File "/home/vagrant/.virtualenvs/powerdash/local/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 211, in init
    extra_ignore_dirs = extra_ignore_dirs)
  File "/home/vagrant/.virtualenvs/powerdash/local/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 85, in get_all_imports
    raise exc
  File "<unknown>", line 3
    def function(*, foo):
                  ^
SyntaxError: invalid syntax

>cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
```

**Comment by bndr** [comment]
Hm.. I think .tox\ dir should be ignored

**Comment by bndr** [comment]
Should be fixed in the new version.
