### ISSUE TITLE
the 0.4.2 tarball on PyPI is missing the stdlib and mapping files

### ISSUE THREAD

**Issue by GooseYArd** [bndr/pipreqs#46]
after installing pipreqs from source onto a machine, I noticed:

Traceback (most recent call last):
  File "/usr/lib/app/bin/pipreqs", line 9, in <module>
    load_entry_point('pipreqs==0.4.2', 'console_scripts', 'pipreqs')()
  File "/usr/lib/app/lib/python2.7/site-packages/pipreqs-0.4.2-py2.7.egg/pipreqs/pipreqs.py", line 253, in main
    init(args)       
  File "/usr/lib/app/lib/python2.7/site-packages/pipreqs-0.4.2-py2.7.egg/pipreqs/pipreqs.py", line 211, in init
    extra_ignore_dirs = extra_ignore_dirs)
  File "/usr/lib/app/lib/python2.7/site-packages/pipreqs-0.4.2-py2.7.egg/pipreqs/pipreqs.py", line 100, in get_all_imports
    with open(join("stdlib"), "r") as f:
IOError: [Errno 2] No such file or directory: '/usr/lib/app/lib/python2.7/site-packages/pipreqs-0.4.2-py2.7.egg/pipreqs/stdlib'

I didn't get this error when using the wheel file, and couldn't figure out how stdlib and mapping were created. After hunting around, I noticed that earlier releases of pipreqs include the files, as well as the autogenerated tarballs from github. It appears that the 0.4.2 tarball on PyPI with md5=a5c865b9400645abc0330b64ef2f0f16 is the only archive missing the files.

**Comment by bndr** [comment]
Thanks for reporting! This should be fixed in version 0.4.3
