### ISSUE TITLE
ERROR on creating requirements.txt - Probably problems with Meta classes

### ISSUE THREAD

**Issue by HarryLyu** [bndr/pipreqs#55]
When I'm trying to run pipreqs I receive this error.

Mac OS X, Python 2.7.11

MacBook-Pro-User-2:edwin-bot igor$ pipreqs ~/work/edwin/repos/edwin-bot/
ERROR: Failed on file: /Users/igor/work/edwin/repos/edwin-bot/core/event_log.py
Traceback (most recent call last):
  File "/usr/local/bin/pipreqs", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/pipreqs/pipreqs.py", line 258, in main
    init(args)
  File "/Library/Python/2.7/site-packages/pipreqs/pipreqs.py", line 216, in init
    extra_ignore_dirs = extra_ignore_dirs)
  File "/Library/Python/2.7/site-packages/pipreqs/pipreqs.py", line 85, in get_all_imports
    raise exc
  File "<unknown>", line 6
    class AbstractLogDriver(object, metaclass=abc.ABCMeta):
                                             ^
SyntaxError: invalid syntax

**Comment by HarryLyu** [comment]
@akaihola ah, yeah, I use Python 3. Are there any plans to support Python 3?

**Comment by bndr** [comment]
I think it already does, but you're trying to analyze a python 3 project with python 2.7 pipreqs, you need to install it using pip3
