### ISSUE TITLE
--pypi-index argument does not work

### ISSUE THREAD

**Issue by akaihola** [bndr/pipreqs#56]
```
$ pipreqs --pypi-server http://localhost:1234/my-pypi /home/akaihola/mypackage
Usage:
    pipreqs [options] <path>
```

```
$ pipreqs --pypi-server=http://localhost:1234/my-pypi /home/akaihola/mypackage
Usage:
    pipreqs [options] <path>
```

```
$ pipreqs --pypi-server /home/akaihola/mypackage
Traceback (most recent call last):
  File "pipreqs", line 11, in <module>
    load_entry_point('pipreqs', 'console_scripts', 'pipreqs')()
  File "pipreqs/pipreqs.py", line 271, in main
    init(args)
  File "pipreqs/pipreqs.py", line 248, in init
    pypi_server=pypi_server)
  File "pipreqs/pipreqs.py", line 135, in get_imports_info
    response = requests.get("{0}{1}/json".format(pypi_server, item), proxies=proxy)
  File "requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "requests/sessions.py", line 349, in request
    prep = self.prepare_request(req)
  File "requests/sessions.py", line 287, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "requests/models.py", line 287, in prepare
    self.prepare_url(url, params)
  File "requests/models.py", line 338, in prepare_url
    "Perhaps you meant http://{0}?".format(url))
requests.exceptions.MissingSchema: Invalid URL u'Trueipython/json':
No schema supplied. Perhaps you meant http://Trueipython/json?
```

**Comment by bndr** [comment]
This was released in version 0.4.5
