### ISSUE TITLE
TabError and SyntaxError when running pipreqs in downloaded repos

### ISSUE THREAD

**Issue by jeremykohn** [bndr/pipreqs#60]
After installing pipreqs and running it in the current directory, an error warns that the file is mixing tabs and spaces:

```
$ pip install pipreqs

Collecting pipreqs
  Using cached pipreqs-0.4.6-py2.py3-none-any.whl
Collecting docopt (from pipreqs)
Collecting yarg (from pipreqs)
  Using cached yarg-0.1.9-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests in /Applications/anaconda/envs/call-data/lib/python3.5/site-packages (from yarg->pipreqs)
Installing collected packages: docopt, yarg, pipreqs
Successfully installed docopt-0.6.2 pipreqs-0.4.6 yarg-0.1.9

You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


$ pipreqs .

ERROR: Failed on file: ./CallScore/classes/text_model.py
Traceback (most recent call last):
  File "/Applications/anaconda/envs/call-data/bin/pipreqs", line 11, in <module>
    sys.exit(main())
  File "/Applications/anaconda/envs/call-data/lib/python3.5/site-packages/pipreqs/pipreqs.py", line 271, in main
    init(args)
  File "/Applications/anaconda/envs/call-data/lib/python3.5/site-packages/pipreqs/pipreqs.py", line 225, in init
    extra_ignore_dirs = extra_ignore_dirs)
  File "/Applications/anaconda/envs/call-data/lib/python3.5/site-packages/pipreqs/pipreqs.py", line 86, in get_all_imports
    raise exc
  File "/Applications/anaconda/envs/call-data/lib/python3.5/site-packages/pipreqs/pipreqs.py", line 72, in get_all_imports
    tree = ast.parse(contents)
  File "/Applications/anaconda/envs/call-data/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 431
    recall_divisor = positives[category]+false_negatives[category]
                                                                 ^
TabError: inconsistent use of tabs and spaces in indentation
```

And when running it in a different directory (another downloaded GitHub repo), it throws an error due to invalid syntax:

```
$ pipreqs .
ERROR: Failed on file: ./<filename>.py
Traceback (most recent call last):
  File "/Applications/anaconda/envs/get-requirements/bin/pipreqs", line 11, in <module>
    sys.exit(main())
  File "/Applications/anaconda/envs/get-requirements/lib/python3.5/site-packages/pipreqs/pipreqs.py", line 271, in main
    init(args)
  File "/Applications/anaconda/envs/get-requirements/lib/python3.5/site-packages/pipreqs/pipreqs.py", line 225, in init
    extra_ignore_dirs = extra_ignore_dirs)
  File "/Applications/anaconda/envs/get-requirements/lib/python3.5/site-packages/pipreqs/pipreqs.py", line 86, in get_all_imports
    raise exc
  File "/Applications/anaconda/envs/get-requirements/lib/python3.5/site-packages/pipreqs/pipreqs.py", line 72, in get_all_imports
    tree = ast.parse(contents)
  File "/Applications/anaconda/envs/get-requirements/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 10
    print 'You must provide an host and index to backfill (ex: east_qa v5.cdr.201608). Exiting...'
                                                                                                 ^
SyntaxError: invalid syntax
```

This might be the fault of the Python scripts that pipreqs is analyzing, if those scripts are badly written, but I would like to troubleshoot and make sure I know what the issue is.

**Comment by jonafato** [comment]
These are Python 3 syntax errors and not a feature (or bug) in `pipreqs`. If the errors are fixed, `pipreqs` will most likely work just fine.
