### ISSUE TITLE
Python 3.6 support?

### ISSUE THREAD

**Issue by nikolay** [bndr/pipreqs#68]

**Comment by bndr** [comment]
It works with python 3.5 so it should probably work with 3.6, haven't really tested it with that version. If someone can report if they used it with python 3.6, it would be nice.

**Comment by irfan-zoefit** [comment]
Not working with Python 3.5 either. It throws an error.

```shell
pipreqs /home/irfan/appify/zoefitcore
ERROR: Failed on file: /home/irfan/appify/zoefitcore/spaCy/examples/inventory_count/inventory.py
Traceback (most recent call last):
  File "/home/irfan/.env3.5/bin/pipreqs", line 11, in <module>
    sys.exit(main())
  File "/home/irfan/.env3.5/lib/python3.5/site-packages/pipreqs/pipreqs.py", line 281, in main
    init(args)
  File "/home/irfan/.env3.5/lib/python3.5/site-packages/pipreqs/pipreqs.py", line 235, in init
    extra_ignore_dirs=extra_ignore_dirs)
  File "/home/irfan/.env3.5/lib/python3.5/site-packages/pipreqs/pipreqs.py", line 86, in get_all_imports
    raise exc
  File "/home/irfan/.env3.5/lib/python3.5/site-packages/pipreqs/pipreqs.py", line 72, in get_all_imports
    tree = ast.parse(contents)
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 24
    print '-------------Inventory Count------------'
                                                   ^
SyntaxError: Missing parentheses in call to 'print'

```

**Comment by jonafato** [comment]
@irfan-zoefit It looks like you're running `pipreqs` on a code base that includes the spaCy examples (in particular, [this file](https://github.com/explosion/spaCy/blob/88ca82bfa64f01ba70bbd2b4be9466113d32c1a7/examples/inventory_count/inventory.py)), which includes Python 2-only code.`pipreqs` is compiling this code, so when run under Python 3, it fails with syntax errors.

If your code base is Python 2, you should probably use `pipreqs` with Python 2, as well. If your project has mixed Python 2-only and / or Python 3-only code, `pipreqs` likely won't work.

**Comment by liushu309** [comment]
I have the same problem. When I run "pipreqs ./ --encoding=utf8"

  File "d:\develope\anaconda3\envs\py35_tf\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 157
    print '--annotation_type expected value is 1 or 2.'
                                                      ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by medlin01GA** [comment]
> 
> 
> I have the same problem. When I run "pipreqs ./ --encoding=utf8"
> 
> File "d:\develope\anaconda3\envs\py35_tf\lib\ast.py", line 35, in parse
> return compile(source, filename, mode, PyCF_ONLY_AST)
> File "", line 157
> print '--annotation_type expected value is 1 or 2.'
> ^
> SyntaxError: Missing parentheses in call to 'print'

I get same error in file `ast.py` under Python 3.6

**Comment by Laurel-rao** [comment]
```
  File "d:\environment\python3.6\lib\site-packages\pipreqs\pipreqs.py", line 138, in get_all_imports
    raise exc
  File "d:\environment\python3.6\lib\site-packages\pipreqs\pipreqs.py", line 124, in get_all_imports
    tree = ast.parse(contents)
  File "d:\environment\python3.6\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 19
    print cmd
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(cmd)?

```
I get same error in file ast.py under Python 3.6

**Comment by mnedelko** [comment]
Any updates on this?

**Comment by fillipesansilva** [comment]
Any updates on this?

**Comment by lu-fr** [comment]
Still experiencing this issue.

**Comment by Carol-gutianle** [comment]
Still experiencing this issue.
