### ISSUE TITLE
syntax error when running pipreqs

### ISSUE THREAD

**Issue by PadamSethia** [bndr/pipreqs#71]
Here's the error 
```

Traceback (most recent call last):
  File "/usr/local/bin/pipreqs", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pipreqs/pipreqs.py", line 281, in main
    init(args)
  File "/usr/local/lib/python2.7/dist-packages/pipreqs/pipreqs.py", line 235, in init
    extra_ignore_dirs=extra_ignore_dirs)
  File "/usr/local/lib/python2.7/dist-packages/pipreqs/pipreqs.py", line 86, in get_all_imports
    raise exc
  File "<unknown>", line 22
    async def concat_async(async_gen):
            ^
SyntaxError: invalid syntax

```

**Comment by bndr** [comment]
You're trying to parse a python3 project with python2 version of library. The AST module used in the pipreqs expects the code to be of the same python version as pipreqs was installed with.

**Comment by PadamSethia** [comment]
So , should I add the python 2.7 shebang on all of my files ?
