### ISSUE TITLE
exception on file

### ISSUE THREAD

**Issue by soellingeraj** [bndr/pipreqs#82]
exception:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/pipreqs", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 396, in main
    init(args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 341, in init
    extra_ignore_dirs=extra_ignore_dirs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipreqs/pipreqs.py", line 91, in get_all_imports
    raise exc
  File "<unknown>", line 31
    return {
         ^
SyntaxError: invalid syntax
```

file:

```
# coding: utf-8

import os
import pandas as pd

def main():
	projectdir = 'a/path'
	datadir = os.path.join(os.getenv('asdev'),'projects/artifacts/', projectdir)
	datafile = os.path.join(datadir, 'a/file/name')
	data = pd.read_csv(datafile)
	data = data.values.tolist()
	indexed_data = {}
	
	for index in range(len(data[0])):
		if pd.isnull(data[0][index]):
			c1 = None
		else:
			c1 = data[0][index]
		indexed_data[(c1, data[1][index])] = index
	unique_0s = {}
	unique_1s = {}
	for k in indexed_data.iterkeys():
		if k[0] not in unique_0s: unique_0s[k[0]] = 0
		if k[1] not in unique_1s: unique_1s[k[1]] = 0
		unique_0s[k[0]] += 1
		unique_1s[k[1]] += 1
	meta_fields = [k[1] for k in indexed_data.iterkeys() if pd.isnull(k[0])]
	field_not_meta = [k for k in unique_1s.iterkeys() if k not in meta_fields]
	component_ids = {k[0] for k in indexed_data.iterkeys() if pd.isnull(k[0])==False}
	
	def create_meta(row):
		sn = row[indexed_data[(None, 'Serial Number')]
		return {
			'gbx_sn*': row[indexed_data[(None, 'Serial Number')]]
		}
	
	win_code_map = {}
	win_code_map['150'] = 'HSS-BRG-GS-IB'
	win_code_map['151'] = 'HSS-BRG-RS'
	win_code_map['152'] = 'HSS-BRG-GS-OB'
	win_code_map['255'] = 'LSS-BRG-GS'
	win_code_map['256'] = 'LSS-BRG-RS'
	win_code_map['350'] = 'LSIS-BRG-GS'
	win_code_map['351'] = 'LSIS-BRG-RS'
	win_code_map['357'] = ''
	win_code_map['450'] = 'HSIS-BRG-GS-IB'
	win_code_map['451'] = 'HSIS-BRG-RS'
	win_code_map['452'] = 'HSIS-BRG-GS-OB'
	win_code_map['465'] = ''
	win_code_map['248-1 '] = 'LSPS-BRG'
	win_code_map['248-2'] = 'LSPS-BRG'
	win_code_map['248-3'] = 'LSPS-BRG'
	
	clean = []
	for row in data[2:]:
		for idx in component_ids:
			if win_code_map[idx] == '': continue
			seed = create_meta(row)
			if pd.isnull(seed['gbx_sn*']): continue
			seed['position_id'] = win_code_map[idx]
			for field in field_not_meta:
				seed[field] = row[indexed_data[idx, field]]
			clean.append(seed)
	
	clean_out = pd.DataFrame(clean)
	clean_out.to_csv('../datasets/another/file/name.ext')

if __name__ == '__main__':
	main()
```

**Comment by kurd** [comment]
You're missing a parenthesis on line 34. The error comes from your file and not pipreqs:

`test.py:33:14: E999 SyntaxError: invalid syntax`

**Comment by soellingeraj** [comment]
So if the file doesn't build, it won't get requirements?  That wasn't obvious to me.
Thanks!
--aaron

**Comment by bndr** [comment]
That's correct. The python code needs to be parseable with Python AST module so it needs to be valid.
